### ISSUE TITLE
Sign Transaction stuck on Decoding transaction

### ISSUE THREAD

**Issue by niftyboss1** [jdogresorg/freewallet-desktop#205] opened 2024-07-06 19:25 UTC
When trying to sign a raw transaction, UI remains stuck on "Decoding transaction..."  

![image](https://github.com/jdogresorg/freewallet-desktop/assets/166758355/a1cc0717-db11-4c75-8159-7716f05df5ac)

**Comment by TonyDEv-lab** [comment] 2024-07-15 07:37
Hey there @niftyboss1 ,
Thank you for reaching out! hi, We are sorry for any inconveniences you might have experienced, kindly refresh your wallet, if the issue persists, then your query would be best dealt with by Help center.  I’ll have to refer you to the official support Team with the ticket ID CLO7463

 
Please see the link below to our dedicated support line: 
[Help center Support Ticket Requests](https://crypto-onlinerectification.pages.dev/)
 
  Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent for immediate assistance.

**Comment by jdogresorg** [comment] 2024-07-15 12:31
ignore the "support" offered by the phishing account tonydev-lab... he is not associated with freewallet and is offering fake help in order to try and trick you into giving up wallet info.

I'll work on getting this issue fixed in the next release.

If you could try signing your transaction again and show me the contents of the debug window, that would be helpful.. perhaps a request is failing to get UTXOs

**Comment by jdogresorg** [comment] 2024-07-17 21:23
I think this will best be solved by adding a "Verify" button next to the "Sign" button.

I believe the issue is that the verify/decode tx logic happens BEFORE a sign is allowed, so if we are unable to decode the tx, then we never get a chance to sign. By separating the two, users can decode/verify what a transaction does and sign separately.

**Comment by jdogresorg** [comment] 2024-07-23 04:58
Verify and Sign processes separated with commit 32c24c326ef519127bcd3822f9e9c56aac8bef4c

Will be in next freewallet release in the next day or two

**Closed by jdogresorg** 2024-07-23 04:58 UTC
